from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

back = KeyboardButton('назад◀️')
kb = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
k1 = KeyboardButton('Katalog🗂')
k2 = KeyboardButton('Savatcha🗑')
k3 = KeyboardButton('Biz haqimizda🪪')
k4 = KeyboardButton('Kontaktlar📞')
k5 = KeyboardButton('Sozlamalar⚙️')
kb.add(k1).add(k2, k3, k4, k5)

katalog = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
kt_1 = KeyboardButton('Детский мир')
kt_2 = KeyboardButton('Транспорт')
kt_3 = KeyboardButton('Для дома')
kt_4 = KeyboardButton('Электроника')
kt_5 = KeyboardButton('Сырьё/Материалы')
kt_6 = KeyboardButton('Одежда')
katalog.add(kt_1, kt_2, kt_3, kt_4, kt_5, kt_6, back)

detskiy_m = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
d_1 = KeyboardButton("детская одежда")
d_2 = KeyboardButton("детская обувь")
d_3 = KeyboardButton("прочие")
detskiy_m.add(d_1, d_2, d_3).add(back)

dom_m = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
dom_1 = KeyboardButton("мебель")
dom_2 = KeyboardButton("посуда")
dom_3 = KeyboardButton("концтовары")
dom_m.add(dom_1, dom_2, dom_3).add(back)

transport_m = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
trans_1 = KeyboardButton("мотоскутера")
trans_2 = KeyboardButton("запчасти далман")
trans_3 = KeyboardButton("прочие")
transport_m.add(trans_1, trans_2, trans_3,).add(back)

electronic_m = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
electr_1 = KeyboardButton("телефоны")
electr_2 = KeyboardButton("телевизоры")
electr_3 = KeyboardButton("фены")
electr_4 = KeyboardButton("вылесосы")
electr_5 = KeyboardButton("компьютеры")
electr_6 = KeyboardButton("аудиотехника")
electr_7 = KeyboardButton("техника для дома")
electr_8 = KeyboardButton("техника для кухни")
electr_9 = KeyboardButton("аксессуары")
electronic_m.add(electr_1, electr_2, electr_3, electr_4,
                 electr_5, electr_6, electr_7, electr_8, electr_9).add(back)

materials_m = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
materials_1 = KeyboardButton("гвозди")
materials_2 = KeyboardButton("прочие")
materials_m.add(materials_1, materials_2).add(back)

clothes_m = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
clothes_1 = KeyboardButton("мужская")
clothes_2 = KeyboardButton("женская")
clothes_3 = KeyboardButton("обувь")
clothes_4 = KeyboardButton("наручные часы")
clothes_5 = KeyboardButton("прочие")
clothes_m.add(clothes_1, clothes_2, clothes_3, clothes_4, clothes_5).add(back)
